### ISSUE TITLE
How can I start to train with self play?

### ISSUE THREAD

**Issue by apollo-time** [Zeta36/chess-alpha-zero#12]
How can I start to train chess without any data?
run Player, Trainer, Evaluator simultaneously so that run 3 processes same time or sequentially so  that run 1 process any time?
If I need to run simultaneously, how can process data synchronize?

**Comment by Zeta36** [comment]
Yes, you have to run simultaneously 3 python scripts:

```
python src/chess_zero/run.py self
python src/chess_zero/run.py opt
python src/chess_zero/run.py eval
```

"If I need to run simultaneously, how can process data synchronize?"
All the synchronization is due to the use of Keras saved model files (weights and configuration). The workers 'opt' and 'self' in each iteration always read the "best model" file, and the 'eval' worker is the one in charge to evaluate each next generation model (created by 'opt') against the "best model". If next generation model play better it becomes the new "best model" and so on.

Indeed, DeepMind used an very similar approximation to an evolutionary algorithm with selection by tournament.

Regards.
